name: List Secrets
on:   
  workflow_dispatch:
    inputs:
      targetRepo: 
        description: 'Environment (dev, stage, prod)'
        required: true
        
jobs:
  Pull-Secrets:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      # List out repository details
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The job was automatically triggered by a ${{ github.event_name }} event."
          echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          
      - name: Step 2 - view the repo secrets context
        run: echo "$SECRETS_CONTEXT" | sed 's/./& /g'
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}

      - name: Step 3 - view the environment secrets
        env:
          COSMOS_DB: ${{  toJson(secrets.COSMOS_DB) }}
          KUBE_CONFIG: ${{  toJson(secrets.KUBE_CONFIG) }}
        run: |
          echo KEY: "$COSMOS_DB" | sed 's/./& /g'
          echo KEY: "$KUBE_CONFIG" | sed 's/./& /g'
