name: List Secrets
on:   
  workflow_dispatch:
    inputs:
      environment: 
        description: 'Environment (dev, stage, prod)'
        required: true
        
jobs:
  Pull-Secrets:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      # List out repository details
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The job was automatically triggered by a ${{ github.event_name }} event."
          echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          
      - name: Step 2 - view the repo secrets context
        run: echo "$SECRETS_CONTEXT" | sed 's/./& /g'
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
